export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export VIRTUAL_ENV_DISABLE_PROMPT=1
export PIP_REQUIRE_VIRTUALENV=false
export CLICOLOR=1
export MOZ_USE_XINPUT2=1
export BASE16_THEME=default-dark
