#!/bin/sh

per=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $2}')
state=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $2}')

case $state in
    charging)
        state="(C)"
        ;;
    *)
        state=""
        ;;
esac

echo $per $state
