#!/bin/sh

vol="$(amixer get Master | grep %)"

if [[ $vol =~ .*off.* ]]
then
    level="off"
else
    level=$(echo $vol | cut -d "[" -f2 | cut -d "]" -f1)
fi

case $1 in
    -t)
        amixer set 'Master' toggle
        pkill -RTMIN+2 i3blocks
        ;;
    -r)
        amixer set 'Master' 5%+
        pkill -RTMIN+2 i3blocks
        ;;

    -l)
        amixer set 'Master' 5%-
        pkill -RTMIN+2 i3blocks
        ;;

    -i)
        echo $level
        ;;
esac

ID=$(cat $HOME/.i3/.dunst_volume)
if [ $ID -gt "0" ]
then
    dunstify -p -r $ID "Volume: $level" >$HOME/.i3/.dunst_volume
else
    dunstify -p "Volume: $level" >$HOME/.i3/.dunst_volume
fi



